"""profiles_and_m2m

Revision ID: 141b2777c747
Revises: d96deed7e5da
Create Date: 2026-05-13 16:32:46.980308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141b2777c747'
down_revision: Union[str, Sequence[str], None] = 'd96deed7e5da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender_id', sa.Integer(), nullable=False),
    sa.Column('looking_for_age_min', sa.Integer(), nullable=False),
    sa.Column('looking_for_age_max', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('own_vibe_id', sa.Integer(), nullable=False),
    sa.Column('desired_vibe_id', sa.Integer(), nullable=False),
    sa.Column('main_media_type', sa.String(length=16), nullable=False),
    sa.Column('main_media_file_id', sa.String(length=256), nullable=False),
    sa.Column('music_file_id', sa.String(length=256), nullable=True),
    sa.Column('video_note_file_id', sa.String(length=256), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("main_media_type IN ('photo', 'video', 'gif')", name=op.f('ck_profiles_main_media_type_allowed')),
    sa.CheckConstraint('age >= 0', name=op.f('ck_profiles_age_non_negative')),
    sa.CheckConstraint('looking_for_age_min <= looking_for_age_max', name=op.f('ck_profiles_looking_for_age_range_valid')),
    sa.ForeignKeyConstraint(['desired_vibe_id'], ['vibes.id'], name=op.f('fk_profiles_desired_vibe_id_vibes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gender_id'], ['genders.id'], name=op.f('fk_profiles_gender_id_genders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['own_vibe_id'], ['vibes.id'], name=op.f('fk_profiles_own_vibe_id_vibes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_profiles_user_id'))
    )
    op.create_index('ix_profiles_age', 'profiles', ['age'], unique=False)
    op.create_index('ix_profiles_is_active_is_hidden', 'profiles', ['is_active', 'is_hidden'], unique=False)
    op.create_table('profile_desired_fandoms',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('fandom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fandom_id'], ['fandoms.id'], name=op.f('fk_profile_desired_fandoms_fandom_id_fandoms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_profile_desired_fandoms_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'fandom_id', name=op.f('pk_profile_desired_fandoms'))
    )
    op.create_table('profile_fandoms',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('fandom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fandom_id'], ['fandoms.id'], name=op.f('fk_profile_fandoms_fandom_id_fandoms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_profile_fandoms_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'fandom_id', name=op.f('pk_profile_fandoms'))
    )
    op.create_table('profile_interests',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], name=op.f('fk_profile_interests_interest_id_interests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_profile_interests_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'interest_id', name=op.f('pk_profile_interests'))
    )
    op.create_table('profile_looking_for_genders',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('gender_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gender_id'], ['genders.id'], name=op.f('fk_profile_looking_for_genders_gender_id_genders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_profile_looking_for_genders_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'gender_id', name=op.f('pk_profile_looking_for_genders'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_looking_for_genders')
    op.drop_table('profile_interests')
    op.drop_table('profile_fandoms')
    op.drop_table('profile_desired_fandoms')
    op.drop_index('ix_profiles_is_active_is_hidden', table_name='profiles')
    op.drop_index('ix_profiles_age', table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
