"""moderation_stop_words_log_pending_review

Revision ID: 9f7eb4bc0d54
Revises: 9fee3a9d45f8
Create Date: 2026-05-13 15:33:49.882213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f7eb4bc0d54'
down_revision: Union[str, Sequence[str], None] = '9fee3a9d45f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_moderation_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('target_kind', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('check_type', sa.String(length=16), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('nsfw_score', sa.Float(), nullable=True),
    sa.Column('matched_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("check_type IN ('text', 'nsfw_image')", name=op.f('ck_content_moderation_log_check_type_allowed')),
    sa.CheckConstraint("decision IN ('approved', 'manual_review', 'rejected')", name=op.f('ck_content_moderation_log_decision_allowed')),
    sa.CheckConstraint("target_kind IN ('profile_bio', 'profile_nickname', 'profile_media', 'like_message', 'creator_post_text', 'creator_post_photo', 'complaint_comment')", name=op.f('ck_content_moderation_log_target_kind_allowed')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_content_moderation_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_moderation_log'))
    )
    op.create_index('ix_content_moderation_log_target_kind_decision', 'content_moderation_log', ['target_kind', 'decision'], unique=False)
    op.create_index('ix_content_moderation_log_user_id_created_at', 'content_moderation_log', ['user_id', 'created_at'], unique=False)
    op.create_table('stop_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=256), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('hate_speech', 'link', 'adult_keyword', 'other')", name=op.f('ck_stop_words_category_allowed')),
    sa.CheckConstraint("kind IN ('word', 'regex')", name=op.f('ck_stop_words_kind_allowed')),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], name=op.f('fk_stop_words_created_by_admin_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stop_words')),
    sa.UniqueConstraint('pattern', 'kind', name='uq_stop_words_pattern_kind')
    )
    op.create_index('ix_stop_words_kind_is_active', 'stop_words', ['kind', 'is_active'], unique=False)
    op.add_column('creator_post_photos', sa.Column('is_pending_review', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('creator_posts', sa.Column('is_pending_review', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('profiles', sa.Column('is_pending_review', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'is_pending_review')
    op.drop_column('creator_posts', 'is_pending_review')
    op.drop_column('creator_post_photos', 'is_pending_review')
    op.drop_index('ix_stop_words_kind_is_active', table_name='stop_words')
    op.drop_table('stop_words')
    op.drop_index('ix_content_moderation_log_user_id_created_at', table_name='content_moderation_log')
    op.drop_index('ix_content_moderation_log_target_kind_decision', table_name='content_moderation_log')
    op.drop_table('content_moderation_log')
    # ### end Alembic commands ###
