"""moderation_promo_analytics

Revision ID: 9fee3a9d45f8
Revises: ba3a3f9ad7cd
Create Date: 2026-05-13 15:20:16.260104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fee3a9d45f8'
down_revision: Union[str, Sequence[str], None] = 'ba3a3f9ad7cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_analytics_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_events'))
    )
    op.create_index('ix_analytics_events_event_type_created_at', 'analytics_events', ['event_type', 'created_at'], unique=False)
    op.create_index('ix_analytics_events_user_id', 'analytics_events', ['user_id'], unique=False)
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('reason_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('moderator_user_id', sa.Integer(), nullable=True),
    sa.Column('moderator_note', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('new', 'in_progress', 'resolved', 'rejected')", name=op.f('ck_complaints_status_allowed')),
    sa.CheckConstraint('from_user_id <> target_user_id', name=op.f('ck_complaints_no_self_complaint')),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('fk_complaints_from_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moderator_user_id'], ['users.id'], name=op.f('fk_complaints_moderator_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reason_id'], ['complaint_reasons.id'], name=op.f('fk_complaints_reason_id_complaint_reasons'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name=op.f('fk_complaints_target_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaints'))
    )
    op.create_index('ix_complaints_status_created_at', 'complaints', ['status', 'created_at'], unique=False)
    op.create_index('ix_complaints_target_user_id', 'complaints', ['target_user_id'], unique=False)
    op.create_table('promo_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('media_file_id', sa.String(length=256), nullable=True),
    sa.Column('media_type', sa.String(length=16), nullable=True),
    sa.Column('target_segment', sa.String(length=16), nullable=False),
    sa.Column('target_user_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('delivered_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.CheckConstraint("media_type IS NULL OR media_type IN ('photo', 'video', 'animation')", name=op.f('ck_promo_posts_media_type_allowed')),
    sa.CheckConstraint("status IN ('draft', 'queued', 'sending', 'sent', 'failed')", name=op.f('ck_promo_posts_status_allowed')),
    sa.CheckConstraint("target_segment IN ('all', 'free', 'premium', 'custom')", name=op.f('ck_promo_posts_target_segment_allowed')),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], name=op.f('fk_promo_posts_created_by_admin_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promo_posts'))
    )
    op.create_index('ix_promo_posts_status', 'promo_posts', ['status'], unique=False)
    op.create_table('promo_post_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'sent', 'failed')", name=op.f('ck_promo_post_recipients_status_allowed')),
    sa.ForeignKeyConstraint(['promo_post_id'], ['promo_posts.id'], name=op.f('fk_promo_post_recipients_promo_post_id_promo_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_promo_post_recipients_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promo_post_recipients')),
    sa.UniqueConstraint('promo_post_id', 'user_id', name='uq_promo_post_recipients_promo_post_id_user_id')
    )
    op.create_index('ix_promo_post_recipients_promo_post_id_status', 'promo_post_recipients', ['promo_post_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_promo_post_recipients_promo_post_id_status', table_name='promo_post_recipients')
    op.drop_table('promo_post_recipients')
    op.drop_index('ix_promo_posts_status', table_name='promo_posts')
    op.drop_table('promo_posts')
    op.drop_index('ix_complaints_target_user_id', table_name='complaints')
    op.drop_index('ix_complaints_status_created_at', table_name='complaints')
    op.drop_table('complaints')
    op.drop_index('ix_analytics_events_user_id', table_name='analytics_events')
    op.drop_index('ix_analytics_events_event_type_created_at', table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
